### ISSUE TITLE
pam-1.6.0 build error: too few arguments to function '_pam_parse_conf_file'

### ISSUE THREAD

**Issue by hdejin** [linux-pam/linux-pam#736]
I'm trying to build 1.6.0 and getting this error:

pam_handlers.c:503:30: error: too few arguments to function '_pam_parse_conf_file'
  503 |                     retval = _pam_parse_conf_file(pamh, f, NULL, PAM_T_ANY, 0, 1);

**Comment by ldv-alt** [comment]
Apparently, --enable-read-both-confs configure option is still used.
@BenBE: it's a regression introduced by commit d686b51a7c58a3fc288030384d1de3e4bc0ebeee.

**Comment by BenBE** [comment]
In initial calls to that functions the level argument has to be duplicated; will take a closer look at a fix later today.

**Comment by stoeckmann** [comment]
I have created a PR which fixes this issue.
